apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-rhtap-devfile-multi-component
    app.kubernetes.io/part-of: rhtap-devfile-multi-component
  name: devfile-sample-python-basic-rhtap-devfile-multi-component
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mdsaud-tenant/rhtap-devfile-multi-component/devfile-sample-python-basic-rhtap-devfile-multi-component@sha256:db17773b60f2199925e27aea2ae2f17eb653ea0d499fd7002bd43ca89c63624e
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
